---
4shockblast:
    - Aleksey Kamenev
    - shockblast4
Joe Abene:
    - DOOMMANN
AD_79:
    - psnAD79
Altima Mantoid:
    - AltimaMantoid
Ryan Barreras:
    - DomRem
Andrew Bassett:
    - Andrewb
Selim Benabdelkhalek:
    - Bastard
Bloodite Krypto:
    - BlooditeKrypto
Zvonimir Bužanić:
    - fx02
    - Zvonimir Buzanic
capodecima:
    - jarinL
Vincent Catalaa:
    - Per0xyd
    - PerOxyd
    - Vincent Catalaá
Ch0wW:
    - Choww
Dasa:
    - Sven Huth
Dashiva:
    - Chris Laverdure
DidierTranber:
    - didierbertrand
DoomHero85:
    - GeneralRainbowBacon
    - General Rainbow Bacon
Jan Dousa:
    - "x-jack"
    - xjack
Espi:
    - Esa Repo
Fuccboyflex:
    - slowfreq
Yashar Garibzadeh:
    - gemini09
Mickael Girard:
    - Mickaël Girard
    - MG86
Adam Hegyi:
    - AdamH
Hi Jango:
    - chewy
JC:
    - JCD
William Huber:
    - "[WH]-Wilou84"
Jordo:
    - DrJordo
Andy Kempling:
    - aurikan
Killer5:
    - MrZzul
Konceptz:
    - Konceptzofdeath
Vaclav Kunes:
    - Bolton
Sverre Kvernmo:
    - Cranium
    - Soundblock
Kyle McAwesome:
    - NoobBait
Light_Speed:
    - odysseyofnoises
Daniel Lindgren:
    - Demonlord
Ling:
    - Lingyan203
Brian Martin:
    - Gurlugon
Andrew Martinez:
    - KingMamba48
Method:
    - method_man
Kieran Millar:
    - Melon
Alexander Nikulin:
    - jongo
Radek Pecka:
    - Radeg
Huy Pham:
    - Doom Marine
Thomas Pilger:
    - Panter
Mike Reid:
    - prower
Ryback:
    - Rybacksda
    - Chris Ratcliff
Ian Sabourin:
    - sslasher
Sayeth:
    - SayethAether
Laurent Sebellin:
    - Squonk
Sedlo:
    - Marijo Sedlić
    - Marijo Sedlic
Natalya Shilyaeva:
    - QWERTY
Arno Slagboom:
    - SlagDOOM
Brad Spencer:
    - Vorpal
    - bsp
David Spring:
    - Springy
William Striegl:
    - crate3333
stx-Vile:
    - Drew DeVore
SuperWeaponDude:
    - SWDude
Tezuro:
    - Tezur0
The Green Herring:
    - TGH
Mark Thompson:
    - Pugsley
Twister:
    - mr.twister
Steffen Udluft:
    - Rini
Marko van der Want:
    - Python
Laszlo Vecsei:
    - Waldon
Mike Watson:
    - Cyb
Adam Williamson:
    - AdamW
Xit Vono:
    - Jim Leonard
Roman Yankovsky:
    - Kpa6
Thomas Zajic:
    - GoDfAtHeR
Zan-zan-zawa-veia:
    - Zanzan
    - yakfak
Zero-Master:
    - ZeroMaster010
Zero_uk:
    - ProGamerX56