---
4shockblast:
    - Aleksey Kamenev
    - shockblast4
Joe Abene:
    - DOOMMANN
AD_79:
    - psnAD79
    - Brayden Hart
Richie Agnew:
    - Byras
Akse:
    - Maxim Abreev
    - Maxi Akse
Alfonzo:
    - Gus Knezevich
Altima Mantoid:
    - AltimaMantoid
    - Casey Alvis
Ancalagon:
    - Ancaaalagon
    - ancalagoonn
Andy Olivera:
    - AndyROlivera
Angus:
    - Jochen Schneidau
Anima Zero:
    - Brian Nesser
Archi:
    - D3Archi
Archy:
    - M. Phoenix Dailey
    - archy9752
ArmouredBlood:
    - Christopher Shepherd
BahdKo:
    - Laura Herrmann
    - Bad Company
Ryan Barreras:
    - DomRem
Andrew Bassett:
    - Andrewb
Belial:
    - Przemysław Woda
    - Przemyslaw Woda
Selim Benabdelkhalek:
    - Bastard
Binario01:
    - Chris Dufrenne
Gene Bird:
    - Searcher
Bloodite Krypto:
    - BlooditeKrypto
Breezeep:
    - Ringofquaddamage
    - Brezeep
Andrey Budko:
    - entryway
Zvonimir Bužanić:
    - fx02
    - Zvonimir Buzanic
Cannonball:
    - Matt Powell
    - Matthew Powell
capodecima:
    - jarinL
Vincent Catalaa:
    - Per0xyd
    - PerOxyd
    - Vincent Catalaá
Wade Cayton:
    - "Shot-Gun"
Ch0wW:
    - Choww
    - Maëllig Desmottes
    - Maellig Desmottes
Chrozoron:
    - Jonas Feragen
Jaromir Cihak:
    - Jacih
ClumsyDoomer:
    - Vladislav Baymurzin
Blake Cole:
    - "Killer-B"
Dan Crowley:
    - SpinSpyder
Cyberdemon531:
    - John Rovenski
Cycloid:
    - Ric Hardacre
dannebubinga:
    - Daniel Jakobsson
    - loskedanne
darkreaver:
    - Christian Lian
Dasa:
    - Sven Huth
Dashiva:
    - Chris Laverdure
Robby DeCandia:
    - r_rr
Adam Dekan:
    - FrostY
dew:
    - Boris Klimeš
    - Boris Klimes
    - dewsome
    - dewsey
DidierTranber:
    - didierbertrand
Dime:
    - Christopher Dewey
    - KingDime
    - NrGDime
Dislogical:
    - Stéphane Petit
    - Stephane Petit
DonCorleone:
    - Nate River
Yonatan Donner:
    - Zem
DoomHero85:
    - GeneralRainbowBacon
    - General Rainbow Bacon
Jan Dousa:
    - "x-jack"
    - xjack
Terry Dunphy:
    - "T-man"
Electra13x7777:
    - Alex Barney
eLim:
    - eLimzke
    - eLim2g
    - Connor O'Leary
Espi:
    - Esa Repo
Ethh:
    - Ethhoack Ethandphi Exbeess
franckFRAG:
    - Franck Livolant
Fuccboyflex:
    - slowfreq
Nicolas Gandou:
    - Dupre
Yashar Garibzadeh:
    - gemini09
Mickael Girard:
    - Mickaël Girard
    - MG86
Grazza:
    - Graham Burgess
Guiddqd:
    - Guillaume Pierson
Gusta:
    - Adolf Vojta
Bjorn Hamels:
    - df
Ole Hartvigsen:
    - hartvix
Adam Hegyi:
    - AdamH
HexTheRex:
    - SuperDoomer DSJ
Hi Jango:
    - chewy
Hitherto:
    - Andrey Boldt
Keene Ho:
    - Mutlee
Jonathan Hoof:
    - Hunter
William Huber:
    - "[WH]-Wilou84"
Kai-Uwe Humpert:
    - Gazelle
j4rio:
    - Armane15
    - jario
JC:
    - JC Dorne
    - JCD
    - dqhd
Jezs:
    - Jezs_
jmickle:
    - Jerry Mickle
    - jmickle66666666
Jordo:
    - DrJordo
Ranjo Kahluff:
    - Mummi
Andy Kempling:
    - aurikan
Killer5:
    - MrZzul
Kimo XVirus:
    - Karim El-Sheikh
    - KimoXvirus
Tomas Kollar:
    - DeDo
Konceptz:
    - Konceptzofdeath
    - Derek Baker
Michael Kren:
    - SataniC MechaniC
Thomas Kroppen:
    - Poeppy
Vaclav Kunes:
    - Bolton
Sverre Kvernmo:
    - Cranium
    - Soundblock
Kyle McAwesome:
    - NoobBait
    - kcmcawesome
Danny Lancashire:
    - Demonslayer
Benjamin Lauterbach:
    - Cowboy
Kim Lee:
    - Storm
Light_Speed:
    - odysseyofnoises
Sebastian Limbach:
    - Dopefish
Daniel Lindgren:
    - Demonlord
Ling:
    - Lingyan203
Linguica:
    - Andrew Stine
Looper:
    - Paska
    - Mittarimato
loveless:
    - loveless_tv
Kim Lundqvist:
    - N.C.
Jakub Machata:
    - DooMerMan
Jakub Mahdal:
    - Avenger
Brian Martin:
    - Gurlugon
Andrew Martinez:
    - KingMamba48
MD922:
    - Minecraftdude922
Memfis:
    - kuchitsu4
Method:
    - method_man
    - Jakub Razak
Kieran Millar:
    - Melon
NaturalTvventy:
    - Emil Brundage
Never_Again:
    - Serge Marudov
    - tpoppins
Alexander Nikulin:
    - jongo
    - anpdad
Nine Inch Heels:
    - Sure Bowb
Ocelot:
    - Juho Ruohonen
Jakub Olšák:
    - Jakub Olsak
    - Smidge
paymentplan:
    - Victor Taylor
Radek Pecka:
    - Radeg
PenumbraSix:
    - Arnaud Florian
Huy Pham:
    - Doom Marine
Thomas Pilger:
    - PanterD2S
Jakub Puk:
    - Huncd6814
ProInfernape:
    - Philip Buchanan
RamboBones:
    - Adrian Danis
Rayzik:
    - RayziikSenpai
Mike Reid:
    - prower
Relic:
    - Mate Crnčević
    - Mate Crncevic
Ribbiks:
    - Zachary Stephens
    - rbk
Rizera:
    - Ricardo Bischoff
    - 1ntru
rodster:
    - mrbrown
Ryback:
    - Rybacksda
    - Chris Ratcliff
Ian Sabourin:
    - sslasher
SAV88:
    - Artem Safronov
Sayeth:
    - SayethAether
    - Ondrej Vaclavik
Johnathan Scott:
    - Incubus
Josh Sealy:
    - Joshy
Laurent Sebellin:
    - Squonk
Sedlo:
    - Marijo Sedlić
    - Marijo Sedlic
Ser:
    - SerEzER
Natalya Shilyaeva:
    - QWERTY
Skepticist:
    - Monakhov Vladimir
    - skepticist87
Slade:
    - Laszlo Gere
Arno Slagboom:
    - SlagDOOM
Snakes:
    - Brian Knox
Spectre01:
    - rileymartin
    - thisisjimmy12
Brad Spencer:
    - Vorpal
    - bsp
    - vr0p
David Spring:
    - Springy
    - Doom Domain
William Striegl:
    - crate3333
Morten Stromsvold:
    - TBO
stx-Vile:
    - Drew DeVore
SuperWeaponDude:
    - SWDude
Tatsurd-cacocaco:
    - Tatsuya Ito
    - tatsurdcacocaco
TendaMonsta:
    - D'Airon James
    - TendaMonsta [CBD]
Tezuro:
    - Tezur0
The Green Herring:
    - Eric Baker
    - TGH
    - TheGreenHerring
Mark Thompson:
    - Pugsley
TimeOfDeath:
    - eternal slumber
    - TimeOfDeath666
Twister:
    - mr.twister
    - David Ficecec
Steffen Udluft:
    - Rini
Petr Urban:
    - McRocet
Marko van der Want:
    - Python
Laszlo Vecsei:
    - Waldon
Veinen:
    - Veinen22
veovis:
    - veovisRC
Jan Vida:
    - Doomgeek
Martin Vosatka:
    - Titan
Ondrej Vosatka:
    - RaideR
Mike Watson:
    - Cyb
Adam Williamson:
    - AdamW
WingAscendant:
    - Byron
Sam Woodman:
    - Metabolist
Richard Woods:
    - rrwoods
Daiyu Xiaoxiang:
    - Trevor Cheng
Xit Vono:
    - Jim Leonard
    - xitvono
Roman Yankovsky:
    - Kpa6
yaqxsw:
    - CrazyDoomguy
Thomas Zajic:
    - GoDfAtHeR
Zan-zan-zawa-veia:
    - Zanzan
    - yakfak
    - ZZZV
Zero-Master:
    - ZeroMaster010
    - Zero Master
Zero_uk:
    - ProGamerX56
    - George Coote